---
- name: Setup SportStore application environment
  hosts: all
  become: yes
  vars:
    mssql_sa_password: "YourStrong!Passw0rd"
    sql_port: 1433
    app_port: 5000
    sportstore_path: "/vagrant"  # synced folder inside VM


  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker network for SportStore
      docker_network:
        name: sportstore-net
        state: present

    - name: Run SQL Server container
      docker_container:
        name: sportstore-sql
        image: mcr.microsoft.com/mssql/server:2022-latest
        state: started
        restart_policy: always
        networks:
          - name: sportstore-net
        ports:
          - "{{ sql_port }}:1433"
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "{{ mssql_sa_password }}"

    - name: Wait for SQL Server to be ready
      wait_for:
        host: "127.0.0.1"
        port: "{{ sql_port }}"
        delay: 10
        timeout: 60

    - name: Build and run SportStore server container
      docker_container:
        name: sportstore-server
        image: mcr.microsoft.com/dotnet/sdk:6.0

        state: started
        restart_policy: always
        networks:
          - name: sportstore-net
        ports:
          - "{{ app_port }}:80"
        volumes:
          - "{{ sportstore_path }}:/app"


        command: >
          /bin/bash -c "cd /app/src/Server && dotnet restore Server.csproj && dotnet build Server.csproj && dotnet run --urls=http://0.0.0.0:80"

        env:
          DOTNET_Environment: Development
          DOTNET_ConnectionStrings__SqlDatabase: "Server=sportstore-sql,1433;Database=master;User Id=sa;Password={{ mssql_sa_password }};TrustServerCertificate=True"

    - name: Inform user
      debug:
        msg: "SportStore is now running! Access it at http://localhost:{{ app_port }}"
