---
- name: Setup SportStore environment
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name:
          - wget
          - curl
          - apt-transport-https
          - software-properties-common
        state: present

    # Install .NET 9 SDK
    - name: Add Microsoft package repo for .NET
      shell: |
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
      args:
        creates: /etc/apt/sources.list.d/microsoft-prod.list

    - name: Install .NET 9 SDK
      apt:
        name: dotnet-sdk-9.0
        state: present
        update_cache: yes

    # Install SQL Server 2022
    - name: Add Microsoft SQL Server repo
      shell: |
        curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
        add-apt-repository "$(curl -s https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list)"
      args:
        creates: /etc/apt/sources.list.d/mssql-server-2022.list

    - name: Install SQL Server
      apt:
        name: mssql-server
        state: present
        update_cache: yes

    - name: Install SQL Server tools
      apt:
        name:
          - mssql-tools
          - unixodbc-dev
        state: present
        update_cache: yes

    - name: Initialize SQL Server
      shell: |
        MSSQL_SA_PASSWORD='YourStrong!Passw0rd' \
        MSSQL_PID=Developer \
        /opt/mssql/bin/mssql-conf -n setup accept-eula
      args:
        creates: /var/opt/mssql/data

    - name: Enable SQL Server service
      systemd:
        name: mssql-server
        state: started
        enabled: yes
