- name: Setup SportStore application environment using Docker Compose
  hosts: all
  become: yes
  vars:
    sportstore_path: "/vagrant"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - docker.io
          - curl
        state: present
        update_cache: yes

    - name: Install Docker Compose v2
      shell: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
      args:
        executable: /bin/bash

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove old SportStore containers if they exist
      shell: |
        docker rm -f sportstore-sql sportstore-server || true
      args:
        executable: /bin/bash

    - name: Start containers with Docker Compose
      shell: |
        docker compose -f {{ sportstore_path }}/docker-compose.yml up -d --remove-orphans
      args:
        executable: /bin/bash
      register: compose_output
      ignore_errors: no

    - name: Show Docker Compose output
      debug:
        var: compose_output.stdout_lines

    - name: Wait for application to start
      wait_for:
        host: "127.0.0.1"
        port: 5000
        delay: 30
        timeout: 120

    - name: Inform user
      debug:
        msg: "SportStore is now running! Access it at http://localhost:5000"
