services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sportstore-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_DATABASE: "SportStore"
    ports:
      - "1433:1433"
    networks:
      - sportstore-net

  app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: sportstore-server
    ports:
      - "5000:80"
    volumes:
      - ./:/app
    working_dir: /app/src/Server
    command: >
      /bin/bash -c "
      dotnet restore &&
      dotnet build --configuration Release --no-restore &&
      dotnet run --configuration Release --urls=http://0.0.0.0:80
      "
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SqlDatabase: "Server=sportstore-sql;Database=SportStore;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
    depends_on:
      - sqlserver
    networks:
      - sportstore-net

networks:
  sportstore-net:
    driver: bridge
